project_name: fileserver

builds:
  - main: ./cmd/fileserver/main.go
    env:
    - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - 386

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc

brews:
  - homepage: 'https://github.com/fileserver'
    description: 'fileserver - a fileserver'
    github:
      owner: broothie
      name: homebrew-fileserver
